config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "locations#new"

  resource :locations, only: [ :new, :create ]
end

app/models/application_record.rb
class ApplicationRecord
end

app/models/location_weather.rb
class LocationWeather
  include ActiveModel::Model

  attr_reader :temp

  validates :temp, numericality: true, presence: true

  def initialize(temp)
    @temp = temp
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @weather = LocationWeather.new(flash[:temperature]) if flash[:temperature]
  end

  def create
    form_object = CreateLocationWeather.new(location_params[:latitude], location_params[:longitude])

    if form_object.valid?
      response = OpenWeatherService.new(form_object).call
      flash[:temperature] = response.dig(:main, :temp)
      redirect_to new_locations_path
    else
      flash[:alert] = "Bad latitude or longitude."
      redirect_to new_locations_path
    end

  rescue OpenWeatherService::Error => e
    flash[:alert] = e.message
    redirect_to new_locations_path
  end

  private

  def location_params
    params.permit(:latitude, :longitude)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title><%= content_for(:title) || "Weatherapp" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
</head>

<body>
    <h1>Weatherapp</h1>
    <p>
        Super awesome weather app to check Your temperature!
    </p>
    <%= yield %>
</body>

</html>

app/views/locations/new.html.erb
<% if @weather.present? %>
<p>
    Your temperature: <%= @weather.temp %>
</p>
<% end %>

<% flash.each do |key, value| %>
<div class="alert alert-<%= key %>">
    <%= value %>
</div>
<% end %>

<%= form_with(url: locations_path, method: :post, local: true) do |form| %>
<div>
    <%= text_field_tag 'latitude', nil, placeholder: 'Enter Latitude term...' %>
</div>

<div>
    <%= text_field_tag 'longitude', nil, placeholder: 'Enter Longitude term...' %>
</div>

<div>
    <%= submit_tag "Submit" %>
</div>
<% end %>